services:
  drupal:
    image: drupal:9
    ports:
      - 8080:80
    volumes:
      # these are gotten from the image documentation for the defined volumes
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    networks:
      - drupal-server-net


  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - drupal-server-net


  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

networks:
  drupal-server-net:
    driver: bridge

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
